export const ORDER_REQUEST= 'ORDER_REQUEST'
export const ORDER_SUCCESS= 'ORDER_SUCCESS'
export const ORDER_FAIL= 'ORDER_FAIL'

export const ORDER_DETAILS_REQUEST= 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS= 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL= 'ORDER_DETAILS_FAIL'
export const ORDER_DETAILS_RESET= 'ORDER_DETAILS_RESET'

export const PAY_ORDER_REQUEST= 'PAY_ORDER_REQUEST'
export const PAY_ORDER_SUCCESS= 'PAY_ORDER_SUCCESS'
export const PAY_ORDER_FAIL= 'PAY_ORDER_FAIL'
export const PAY_ORDER_RESET = 'PAY_ORDER_RESET'

export const LIST_ORDER_REQUEST= 'LIST_ORDER_REQUEST'
export const LIST_ORDER_SUCCESS= 'LIST_ORDER_SUCCESS'
export const LIST_ORDER_FAIL= 'LIST_ORDER_FAIL'

export const ADMIN_ORDER_REQUEST= 'ADMIN_ORDER_REQUEST'
export const ADMIN_ORDER_SUCCESS= 'ADMIN_ORDER_SUCCESS'
export const ADMIN_ORDER_FAIL= 'ADMIN_ORDER_FAIL'
 


