export const ORDER_REQUEST= 'ORDER_REQUEST'
export const ORDER_SUCCESS= 'ORDER_SUCCESS'
export const ORDER_FAIL= 'ORDER_FAIL'

export const ORDER_DETAILS_REQUEST= 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS= 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL= 'ORDER_DETAILS_FAIL'
export const ORDER_DETAILS_RESET= 'ORDER_DETAILS_RESET'

export const PAY_ORDER_REQUEST= 'PAY_ORDER_REQUEST'
export const PAY_ORDER_SUCCESS= 'PAY_ORDER_SUCCESS'
export const PAY_ORDER_FAIL= 'PAY_ORDER_FAIL'
export const PAY_ORDER_RESET = 'PAY_ORDER_RESET'


