export const PRODUCT_LIST_REQUEST ='PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS ='PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL ='PRODUCT_LIST_FAIL'


export const PRODUCT_DETAILS_REQUEST ='PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS ='PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAIL ='PRODUCT_DETAILS_FAIL'

export const REMOVED_PRODUCT_REQUEST ='REMOVED_PRODUCT_REQUEST'
export const REMOVED_PRODUCT_SUCCESS ='REMOVED_PRODUCT_SUCCESS'
export const REMOVED_PRODUCT_FAIL ='REMOVED_PRODUCT_FAIL'

export const CREATE_PRODUCT_REQUEST ='CREATE_PRODUCT_REQUEST'
export const CREATE_PRODUCT_SUCCESS ='CREATE_PRODUCT_SUCCESS'
export const CREATE_PRODUCT_FAIL ='CREATE_PRODUCT_FAIL'
export const CREATE_PRODUCT_RESET ='CREATE_PRODUCT_RESET'

export const  UPDATE_PRODUCT_REQUEST =' UPDATE_PRODUCT_REQUEST'
export const  UPDATE_PRODUCT_SUCCESS =' UPDATE_PRODUCT_SUCCESS'
export const  UPDATE_PRODUCT_FAIL =' UPDATE_PRODUCT_FAIL'
export const  UPDATE_PRODUCT_RESET =' UPDATE_PRODUCT_RESET'