export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET'

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL'
export const UPDATE_PROFILE_RESET = 'UPDATE_PROFILE_RESET'

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAIL = 'USER_LIST_FAIL'
export const USER_LIST_RESET = 'USER_LIST_RESET'

 export const REMOVE_USER_REQUEST = 'REMOVE_USER_REQUEST'
 export const REMOVE_USER_SUCCESS = 'REMOVE_USER_SUCCESS'
 export const REMOVE_USER_FAIL = 'REMOVE_USER_FAIL'

export const UPDATE_USER_BY_ADMIN_REQUEST = 'UPDATE_USER_BY_ADMIN_REQUEST'
export const UPDATE_USER_BY_ADMIN_SUCCESS = 'UPDATE_USER_BY_ADMIN_SUCCESS'
export const UPDATE_USER_BY_ADMIN_FAIL = 'UPDATE_USER_BY_ADMIN_FAIL'
export const UPDATE_USER_BY_ADMIN_RESET = 'UPDATE_USER_BY_ADMIN_RESET'