const products =[
    {
        _id:'1',
        name:'lady',
        image:'/image/shows.png',
        description:"Lady Dior is a commercial name given to a handbag by the Christian Dior company in honor of Diana, Princess of Wales.",
        brand:'Apple',
        category:'Bag',
        price: 20.9,
        countInStock:3,
        rating:3.5,
        numReviews:4,
    },  
    {
        _id:'2',
        name:'watch',
        image:'/image/daniel-korpai-hbTKIbuMmBI-unsplash.jpg',
        description:"Lady Dior is a commercial name given to a handbag by the Christian Dior company in honor of Diana, Princess of Wales.",
        brand:'Apple',
        category:'Bag',
        price: 20.9,
        countInStock:3,
        rating:2.5,
        numReviews:3,
    },
    
    {
        _id:'3',
        name:'Lady bag',
        image:'/image/laura-chouette-y-f8aJbBHHM-unsplash.jpg',
        description:"Lady Dior is a commercial name given to a handbag by the Christian Dior company in honor of Diana, Princess of Wales.",
        brand:'Apple',
        category:'Bag',
        price: 20.9,
        countInStock:3,
        rating:3.5,
        numReviews:4,
    },  
    {
        _id:'4',
        name:'Lady bag',
        image:'/image/arno-senoner-HFE2RyC76tw-unsplash.jpg',
        description:"Lady Dior is a commercial name given to a handbag by the Christian Dior company in honor of Diana, Princess of Wales.",
        brand:'Apple',
        category:'Bag',
        price: 20.9,
        countInStock:3,
        rating:0.5,
        numReviews:1,
    },
    {
        _id:'5',
        name:'iphone pro 14',
        image:'/image/shardar-tarikul-islam-tIQ2t64FKy8-unsplash.jpg',
        description:"Lady Dior is a commercial name given to a handbag by the Christian Dior company in honor of Diana, Princess of Wales.",
        brand:'Apple',
        category:'Bag',
        price: 20.9,
        countInStock:3,
        rating:1.5,
        numReviews:2,
    },
    
    
    
    
    
    {
        _id:'6',
        name:'Hp laptop',
        image:'/image/dell-SGY0LIfTKZ4-unsplash.jpg',
        description:"Lady Dior is a commercial name given to a handbag by the Christian Dior company in honor of Diana, Princess of Wales.",
        brand:'Apple',
        category:'Bag',
        price: 20.9,
        countInStock:3,
        rating:4.5,
        numReviews:5,
    },
    
    {
        _id:'7',
        name:'Airpods wireless Headphones',
        image:'/image/c-d-x-PDX_a_82obo-unsplash.jpg',
        description:"There are a few good reasons why Apple AirPods are so popular: they're lightweight, easy to use, reliable, offer decent sound-per-pound and bring Siri to life in your ears. Plus, although they work best when used with an Apple product, they can be paired with any Bluetooth device, from smart TVs to smartphones",
        brand:'Apple',
        category:'Electronics',
        price: 89.9,
        countInStock:3,
        rating:3.5,
        numReviews:4,
    },
    {
        _id:'8',
        name:'iphone pro 14',
        image:'/image/laura-chouette-JKOD4x9A79Y-unsplash.jpg',
        description:"Lady Dior is a commercial name given to a handbag by the Christian Dior company in honor of Diana, Princess of Wales.",
        brand:'Apple',
        category:'Bag',
        price: 20.9,
        countInStock:3,
        rating:2.5,
        numReviews:3,
    },
    
]
export default products